on:
  push:
    branches-ignore: [master]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.4"]
    env:
      NOTIFY_SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      NOTIFY_SLACK_NOTIFY_CHANNEL: "oss-notices"
      NOTIFY_CURRENT_REPOSITORY_URL: "${{ github.server_url }}/${{ github.repository }}"
      NOTIFY_TEST_RUN_ID: "${{ github.run_id }}"
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version }}
          bundler-cache: true
      - name: Update Bundle
        run: bundle check || bundle install
      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Test
        run: bin/test

  linter:
    name: Linter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.4"]
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version }}
          bundler-cache: true
      - name: Update Bundle
        run: bundle check || bundle install
      - run: bundle exec standardrb