on:
  push:
    branches-ignore: [master]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.4"]
    env:
      NOTIFY_SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      NOTIFY_SLACK_NOTIFY_CHANNEL: "oss-notices"
      NOTIFY_CURRENT_REPOSITORY_URL: "${{ github.server_url }}/${{ github.repository }}"
      NOTIFY_TEST_RUN_ID: "${{ github.run_id }}"
      CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version }}
          bundler-cache: true
      - name: Update Bundle
        run: bundle check || bundle install
      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - uses: amancevice/setup-code-climate@v2
        with:
          cc_test_reporter_id: ${{ secrets.CC_TEST_REPORTER_ID }}
      - run: cc-test-reporter before-build
      - name: Test
        run: bin/test
      - run: cc-test-reporter after-build
        if: ${{ github.event_name != 'pull_request' }}

  linter:
    name: Linter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.4"]
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version }}
          bundler-cache: true
      - name: Update Bundle
        run: bundle check || bundle install
      - run: bundle exec standardrb